= JSDT demo 01
Patrik Suzzi
Version 1.2, 17.01.2017
:keywords: JSDT, demo, nodejs, bower, npm, javascript, eclipse 
:experimental:

Readme for the code at https://github.com/vogellacompany/codeexamples-javascript/tree/master/com.vogella.jsdt.demo.neon01[com.vogella.jsdt.demo.neon01 on codeexamples-javascript]

This code is related to the vogella tutorial: http://www.vogella.com/tutorials/JavaScript/article.html#jsfrontend[JavaScript Frontend Example]

= Description

*Angular.JS* single page application with _routing_ and _controllers_. 
Styling is done via *Bootstrap* and *FontAwesome*. 
The demo also has a *Node.js* _script_ to launch a local *Express* _server_ to serve the application on localhost.

Prerequisites:: You installed latest Eclipse JSDT or JEE. As JSDT integrates Node.js (and its tools) on your system, you should also have installed Node.js, npm and Bower.

To verify the prerequisites, presse kbd:[Ctrl+Alt+T] to open the command prompt in Eclipse, and type `node -v`, `npm -v` and `bower -v`,  to verify the tools are installed. 
 
== Run the application on Local Server

. To *Build the frontend*, install bower dependencies: r-click on  `bower.json` then select *Run As.. > Bower Install*. This will install the needed dependencies under the `bower_components` folder
. To *Build the node.js infrastructure*, install Node.js dependencies:: R-click `package.json` and select *Run As.. > NPM Install*. This will install the needed dependencies under the `node_modules` folder
. To *Launch the server* on localhost and *open your single page application*, run the node script: R-click `launch-static-server.js` and select *Run As .. > Node.js Application*. This will launch node passing your script as parameter
. To *stop the server*, you can just terminate the process in Eclipse. 

== Cross-origins requests

Angular routing is not intended for working on local files. 
Hence, if you open `index.html` from the file system, you'll see an empty page when launching the page in Chrome.
You can detect the error only by inspecting the page. 

To fix this issue, you'll have to use nodejs to launch a lightweight local server to serve static content, as explained above.

=== Copyright & License

CopyRight (C) Patrik Suzzi, 2016. You can use the software examples free of charge, under the terms of https://www.eclipse.org/legal/epl-v10.html[EPL] license.


